let networks=[],currentScan=null,isAutoScan=false;
function initScanner(){networks=loadNetworks();renderNetworks();updateVisualizer()}
function startScan(){if(currentScan)return;const btn=document.getElementById('scanBtn');btn.classList.add('scanning');document.getElementById('scanIcon').className='fas fa-spinner fa-spin';document.getElementById('scanStatus').textContent='جاري المسح...';const startTime=Date.now();const scanInterval=setInterval(()=>{const elapsed=Math.floor((Date.now()-startTime)/1000);document.getElementById('scanDuration').textContent=formatTime(elapsed)},1000);setTimeout(()=>{clearInterval(scanInterval);performScan();},1500)}
function performScan(){const mockNetworks=generateMockNetworks();networks=[...mockNetworks,...networks.filter(n=>!mockNetworks.find(m=>m.mac===n.mac))];saveNetworks(networks);renderNetworks();updateVisualizer();addToHistory({time:new Date().toISOString(),count:mockNetworks.length});renderHistory();const btn=document.getElementById('scanBtn');btn.classList.remove('scanning');document.getElementById('scanIcon').className='fas fa-search';document.getElementById('scanStatus').textContent='اكتمل المسح';document.getElementById('networkCount').textContent=networks.length+' شبكة';document.getElementById('lastScan').textContent='آخر مسح: '+new Date().toLocaleTimeString('ar');showToast('✅ تم اكتشاف '+mockNetworks.length+' شبكة')}
function generateMockNetworks(){const prefixes=['Home','Office','Guest','IoT','Smart','5G','Fiber','Net','WiFi','TP-Link','D-Link','Cisco','Netgear'];const securities=['WPA2','WPA3','WPA/WPA2','WEP','Open'];const freq2=['2.4 GHz','2.4 GHz','2.4 GHz','2.4 GHz'];const freq5=['5 GHz','5 GHz','5 GHz'];const networks=[];const count=Math.floor(Math.random()*10)+5;for(let i=0;i<count;i++){const is5GHz=Math.random()>0.4;const freq=is5GHz?freq5[Math.floor(Math.random()*freq5.length)]:freq2[Math.floor(Math.random()*freq2.length)];const channel=is5GHz?Math.floor(Math.random()*20)+36:Math.floor(Math.random()*11)+1;const signal=Math.floor(Math.random()*60)+40;const isHidden=Math.random()<0.1;networks.push({id:Date.now()+i,ssid:isHidden?'<Hidden Network>':prefixes[Math.floor(Math.random()*prefixes.length)]+'_'+Math.floor(Math.random()*1000),mac:generateMAC(),signal:signal,frequency:freq,channel:channel,security:securities[Math.floor(Math.random()*securities.length)],encryption:Math.random()>0.3?'AES':'TKIP',maxSpeed:is5GHz?'1.3 Gbps':'450 Mbps',firstSeen:new Date().toISOString(),lastSeen:new Date().toISOString(),hidden:isHidden})}return networks}
function generateMAC(){const hex='0123456789ABCDEF';let mac='';for(let i=0;i<6;i++){if(i>0)mac+=':';mac+=hex[Math.floor(Math.random()*16)]+hex[Math.floor(Math.random()*16)]}return mac}
function toggleAutoScan(){isAutoScan=!isAutoScan;document.getElementById('autoScanBtn').classList.toggle('active',isAutoScan);if(isAutoScan){showToast('🔄 المسح التلقائي مفعل');autoScanInterval=setInterval(startScan,10000)}else{showToast('⏸ المسح التلقائي متوقف');clearInterval(autoScanInterval)}}
function sortNetworks(){networks.sort((a,b)=>b.signal-a.signal);renderNetworks();showToast('📊 تم الترتيب حسب قوة الإشارة')}
function clearNetworks(){if(confirm('هل تريد مسح جميع الشبكات؟')){networks=[];saveNetworks(networks);renderNetworks();updateVisualizer();showToast('🗑 تم مسح الشبكات')}}
function exportData(){const data=JSON.stringify(networks,null,2);const blob=new Blob([data],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='wifi_networks_'+Date.now()+'.json';a.click();URL.revokeObjectURL(url);showToast('📥 تم تصدير البيانات')}
function renderNetworks(){const c=document.getElementById('networkList');if(!networks.length){c.innerHTML='<div class="empty-playlist"><span>📡</span><p>اضغط زر المسح لبدء اكتشاف الشبكات</p></div>';document.getElementById('networkStats').textContent='0 شبكة';return}const filtered=getFilteredNetworks();document.getElementById('networkStats').textContent=filtered.length+' شبكة';c.innerHTML=filtered.map(n=>{const signalBars=generateSignalBars(n.signal);const securityIcon=getSecurityIcon(n.security);return `<div class="network-item" onclick="showNetworkDetails('${n.id}')"><div class="n-icon">${securityIcon}</div><div class="n-info"><div class="n-name">${n.ssid}</div><div class="n-details">${n.frequency} • Ch ${n.channel} • ${n.security}</div></div><div class="n-signal">${signalBars}<span style="font-size:10px;color:var(--accent)">${n.signal}%</span></div><span class="n-del" onclick="event.stopPropagation();deleteNetwork('${n.id}')"><i class="fas fa-times"></i></span></div>`}).join('')}
function generateSignalBars(signal){const bars=Math.ceil(signal/25);let html='<div class="signal-bars">';for(let i=0;i<4;i++){const height=[4,8,12,16][i];html+=`<div class="signal-bar" style="height:${height}px;opacity:${i<bars?1:0.2}"></div>`}html+='</div>';return html}
function getSecurityIcon(security){if(security==='Open')return '🔓';if(security==='WEP')return '⚠️';if(security==='WPA3')return '🛡️';return '🔒'}
function deleteNetwork(id){networks=networks.filter(n=>n.id!==id);saveNetworks(networks);renderNetworks();updateVisualizer();showToast('🗑 تم حذف الشبكة')}
function showNetworkDetails(id){const n=networks.find(n=>n.id===id);if(!n)return;alert(`📡 ${n.ssid}\n\n🔒 الأمان: ${n.security}\n📶 الإشارة: ${n.signal}%\n📡 التردد: ${n.frequency}\n🔢 القناة: ${n.channel}\n💻 MAC: ${n.mac}\n⚡ السرعة: ${n.maxSpeed}`)}
function updateVisualizer(){updateVizData(networks)}
function formatTime(s){return Math.floor(s/60)+':'+(s%60<10?'0':'')+(s%60)}