let networks=[],currentScan=null,isAutoScan=false,autoScanInterval=null;
function initScanner(){networks=loadNetworks();renderNetworks();updateVisualizer();updateStats()}
function startScan(){if(currentScan)return;const btn=document.getElementById('scanBtn');btn.classList.add('scanning');document.getElementById('scanIcon').className='fas fa-spinner fa-spin';document.getElementById('scanStatus').textContent='جاري المسح...';const startTime=Date.now();const totalDuration=3000;const progressInterval=setInterval(()=>{const elapsed=Date.now()-startTime;const progress=Math.min(100,(elapsed/totalDuration)*100);document.getElementById('progressFill').style.width=progress+'%';document.getElementById('progressPercent').textContent=Math.floor(progress)+'%';document.getElementById('scanDuration').textContent=formatTime(Math.floor(elapsed/1000))},100);setTimeout(()=>{clearInterval(progressInterval);performScan();document.getElementById('progressFill').style.width='100%';document.getElementById('progressPercent').textContent='100%';setTimeout(()=>{document.getElementById('progressFill').style.width='0%';document.getElementById('progressPercent').textContent='0%'},500)},totalDuration)}
function performScan(){const mockNetworks=generateMockNetworks();networks=[...mockNetworks,...networks.filter(n=>!mockNetworks.find(m=>m.mac===n.mac))];saveNetworks(networks);renderNetworks();updateVisualizer();updateStats();addToHistory({time:new Date().toISOString(),count:mockNetworks.length});renderHistory();const btn=document.getElementById('scanBtn');btn.classList.remove('scanning');document.getElementById('scanIcon').className='fas fa-search';document.getElementById('scanStatus').textContent='اكتمل المسح';document.getElementById('networkCount').textContent=networks.length+' شبكة';document.getElementById('lastScan').textContent='آخر مسح: '+new Date().toLocaleTimeString('ar');showToast('✅ تم اكتشاف '+mockNetworks.length+' شبكة');if(loadSettings().soundEnabled){playNotificationSound()}}
function generateMockNetworks(){const prefixes=['Home','Office','Guest','IoT','Smart','5G','Fiber','Net','WiFi','TP-Link','D-Link','Cisco','Netgear','ASUS','Xiaomi'];const securities=['WPA2','WPA3','WPA/WPA2','WEP','Open'];const networks=[];const count=Math.floor(Math.random()*15)+10;for(let i=0;i<count;i++){const is5GHz=Math.random()>0.4;const freq=is5GHz?'5 GHz':'2.4 GHz';const channel=is5GHz?Math.floor(Math.random()*20)+36:Math.floor(Math.random()*11)+1;const signal=Math.floor(Math.random()*70)+30;const isHidden=Math.random()<0.1;networks.push({id:Date.now()+i+'_'+Math.random(),ssid:isHidden?'<Hidden Network>':prefixes[Math.floor(Math.random()*prefixes.length)]+'_'+Math.floor(Math.random()*1000),mac:generateMAC(),signal:signal,frequency:freq,channel:channel,security:securities[Math.floor(Math.random()*securities.length)],encryption:Math.random()>0.3?'AES':'TKIP',maxSpeed:is5GHz?'1.3 Gbps':'450 Mbps',firstSeen:new Date().toISOString(),lastSeen:new Date().toISOString(),hidden:isHidden})}return networks}
function generateMAC(){const hex='0123456789ABCDEF';let mac='';for(let i=0;i<6;i++){if(i>0)mac+=':';mac+=hex[Math.floor(Math.random()*16)]+hex[Math.floor(Math.random()*16)]}return mac}
function toggleAutoScan(){const settings=loadSettings();isAutoScan=!isAutoScan;settings.autoScan=isAutoScan;saveSettings(settings);document.getElementById('autoScanBtn').classList.toggle('active',isAutoScan);if(isAutoScan){showToast('🔄 المسح التلقائي مفعل');autoScanInterval=setInterval(startScan,settings.scanInterval*1000)}else{showToast('⏸ المسح التلقائي متوقف');if(autoScanInterval)clearInterval(autoScanInterval)}}
function sortNetworks(){networks.sort((a,b)=>b.signal-a.signal);renderNetworks();showToast('📊 تم الترتيب حسب قوة الإشارة')}
function clearNetworks(){if(confirm('هل تريد مسح جميع الشبكات؟')){networks=[];saveNetworks(networks);renderNetworks();updateVisualizer();updateStats();showToast('🗑 تم مسح الشبكات')}}
function exportData(){const data={exportTime:new Date().toISOString(),totalNetworks:networks.length,networks:networks};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='wifi_scan_'+Date.now()+'.json';a.click();URL.revokeObjectURL(url);showToast('📥 تم تصدير البيانات')}
function renderNetworks(){const c=document.getElementById('networkList');if(!networks.length){c.innerHTML='<div class="empty-playlist"><span>📡</span><p>اضغط زر المسح لبدء اكتشاف الشبكات</p></div>';document.getElementById('networkStats').textContent='0 شبكة';return}const filtered=getFilteredNetworks();document.getElementById('networkStats').textContent=filtered.length+' شبكة';c.innerHTML=filtered.map(n=>{const signalBars=generateSignalBars(n.signal);const securityIcon=getSecurityIcon(n.security);return `<div class="network-item" onclick="showNetworkDetails('${n.id}')"><div class="n-icon">${securityIcon}</div><div class="n-info"><div class="n-name">${n.ssid}</div><div class="n-details">${n.frequency} • Ch ${n.channel} • ${n.security}</div></div><div class="n-signal">${signalBars}<span class="signal-percent">${n.signal}%</span></div><span class="n-del" onclick="event.stopPropagation();deleteNetwork('${n.id}')"><i class="fas fa-times"></i></span></div>`}).join('')}
function generateSignalBars(signal){const bars=Math.ceil(signal/25);let html='<div class="signal-bars">';for(let i=0;i<4;i++){const height=[6,12,18,24][i];html+=`<div class="signal-bar" style="height:${height}px;opacity:${i<bars?1:0.2}"></div>`}html+='</div>';return html}
function getSecurityIcon(security){if(security==='Open')return '🔓';if(security==='WEP')return '⚠️';if(security==='WPA3')return '🛡️';return '🔒'}
function deleteNetwork(id){networks=networks.filter(n=>n.id!==id);saveNetworks(networks);renderNetworks();updateVisualizer();updateStats();showToast('🗑 تم حذف الشبكة')}
function showNetworkDetails(id){const n=networks.find(n=>n.id===id);if(!n)return;document.getElementById('modalTitle').textContent=n.ssid;document.getElementById('modalBody').innerHTML=`<div class="modal-item"><span class="label">🔒 الأمان</span><span class="value">${n.security}</span></div><div class="modal-item"><span class="label">📶 الإشارة</span><span class="value">${n.signal}%</span></div><div class="modal-item"><span class="label">📡 التردد</span><span class="value">${n.frequency}</span></div><div class="modal-item"><span class="label">🔢 القناة</span><span class="value">${n.channel}</span></div><div class="modal-item"><span class="label">💻 MAC</span><span class="value">${n.mac}</span></div><div class="modal-item"><span class="label">⚡ السرعة</span><span class="value">${n.maxSpeed}</span></div><div class="modal-item"><span class="label">🔐 التشفير</span><span class="value">${n.encryption}</span></div>`;document.getElementById('networkModal').classList.add('active')}
function closeModal(){document.getElementById('networkModal').classList.remove('active')}
function updateStats(){document.getElementById('totalNetworks').textContent=networks.length;const secure=networks.filter(n=>n.security!=='Open').length;const open=networks.filter(n=>n.security==='Open').length;document.getElementById('secureNetworks').textContent=secure;document.getElementById('openNetworks').textContent=open;const avgSignal=networks.length?Math.round(networks.reduce((sum,n)=>sum+n.signal,0)/networks.length):0;document.getElementById('avgSignal').textContent=avgSignal+'%'}
function updateVisualizer(){updateVizData(networks)}
function playNotificationSound(){try{const audioCtx=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioCtx.createOscillator();const gainNode=audioCtx.createGain();oscillator.connect(gainNode);gainNode.connect(audioCtx.destination);oscillator.frequency.value=800;gainNode.gain.value=0.3;oscillator.start();setTimeout(()=>{oscillator.stop();audioCtx.close()},200)}catch(e){}}
function formatTime(s){return Math.floor(s/60)+':'+(s%60<10?'0':'')+(s%60)}